### PR TITLE
Avoid the use of the rb_eval_cmd_kw function if it is not available

### LINKED ISSUE #75: tk git head does not compile with ruby4.0.0dev (2025-12-06)
Trying with `ruby 4.0.0dev (2025-12-06 master 0346206d3e) +PRISM [x86_64-linux]`
https://github.com/ruby/ruby/commit/0346206d3eab2a8e659be0dd52aea6fc7b0ebb06

ruby/tk git head ( https://github.com/ruby/tk/commit/6f35a07ffe3ea507d3f108770724fcf0d2d896f1  )
fails to compile as:

```
[mockbuild@e1884f31a42d49c49e2b15f6c152e3f2 tkutil]$ make -j2 -k
gcc -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I. -DHAVE_RB_OBJ_INSTANCE_EXEC -DHAVE_RB_SYM2STR -DHAVE_RB_ID2STR -DHAVE_RB_ARY_CAT -DHAVE_STRNDUP    -fPIC -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -m64 -o tkutil.o -c tkutil.c
tkutil.c: In function 'tk_eval_cmd':
tkutil.c:177:12: error: implicit declaration of function 'rb_eval_cmd_kw'; did you mean 'tk_eval_cmd'? [-Wimplicit-function-declaration]
  177 |     return rb_eval_cmd_kw(cmd, rest, 0);
      |            ^~~~~~~~~~~~~~
      |            tk_eval_cmd
make: *** [Makefile:252: tkutil.o] Error 1
make: Target 'all' not remade because of errors.
```

Most likely due to https://github.com/ruby/ruby/pull/15404 change.

### PR DESCRIPTION
**Pull request by jeremyevans**
Fixes #75

### CODE REVIEW

**Comment by rhenium** [comment]
> While we could continue to use `rb_eval_cmd_kw()`, we should use something else if it is deprecated.

Agreed. AFAIK `mkmf` doesn't provide a straightforward way to check if a function is deprecated or not, so I think it's simpler to remove the `rb_eval_cmd_kw()` usage entirely, regardless of the Ruby version.

IMHO, the functionality provided by `rb_eval_cmd*()` feels somewhat out of place, so deprecating it makes sense to me.

**Comment by jeremyevans** [comment]
> > While we could continue to use `rb_eval_cmd_kw()`, we should use something else if it is deprecated.
> 
> Agreed. AFAIK `mkmf` doesn't provide a straightforward way to check if a function is deprecated or not, so I think it's simpler to remove the `rb_eval_cmd_kw()` usage entirely, regardless of the Ruby version.

Once your Ruby PR is merged, the new code in this PR would not be used. It would only start being used once Ruby actually drops the method. I think that's acceptable. That allows us to keep full backwards compatibility for as long as possible. While I think this PR is backwards compatible, I'm not 100% sure it is in all respects.

If Ruby adds support for checking for deprecated functions, I would be in favor of using it and switching to this new code if deprecation is detected.

> IMHO, the functionality provided by `rb_eval_cmd*()` feels somewhat out of place, so deprecating it makes sense to me.

I agree. I don't know the historical reason behind having a single function that either evaluates a string or calls a proc, instead of having two separate functions.

File: ext/tk/tkutil/tkutil.c [hunk 1]
```diff
@@ -167,14 +167,44 @@ tk_obj_untrust(VALUE self, VALUE obj)
...
+        int pstate;
+        struct tk_eval_cmd_call_args args;
+        VALUE val;
+        args.cmd = cmd;
+        args.argc = RARRAY_LENINT(rest);
+        args.argv = RARRAY_CONST_PTR(rest);
+        val = rb_protect(tk_eval_cmd_call, (VALUE)&args, &pstate);
+        RB_GC_GUARD(rest);
+        return val;
+    }
```
Comment (rhenium) [inline ext/tk/tkutil/tkutil.c]: `rb_eval_cmd_kw()` in https://github.com/ruby/ruby/blob/941e70ab38d01d067b7bbbcdf8553893a9ca8b49/vm_eval.c#L2148-L2179 doesn't suppress exceptions. The `rb_protect()` around the eval and funcall should be unnecessary.

Comment (jeremyevans) [reply ext/tk/tkutil/tkutil.c]: Thank you. I misunderstood the purpose of the tag code in `rb_eval_cmd_call_kw` when trying to recreate the behavior. I'll update the PR.

**Comment by jeremyevans** [comment]
Ruby 4.0 shipped with the fix so the `rb_eval_cmd_kw` function is deprecated but not removed. So `tk` still builds with it, without this change. So there currently isn't a rush to merge this.
