### PR TITLE
Assume Tk 8.* code applies to Tk 9.* as well

### LINKED ISSUE #81: Goldberg widget demo does not work with Ruby/Tk 0.6.0 and tk 9.0.2
Trying with Ruby/Tk 0.6.0 with tk 9.0.2, trying

* chdir: `$ cd sample/demos-en`
* execute: `$ ruby ./widget`
* On gui, click `4. A celebration of Rube Goldberg (if supported)`

Then the following error happens:

```
NoMethodError: undefined method 'index' for nil

---< backtrace of Ruby side >-----
./widget:623:in 'method_missing'
/builddir/GIT/tk/lib/tk/font.rb:203:in 'TkFont.is_system_font?'
/builddir/GIT/tk/lib/tk/font.rb:508:in 'TkFont.init_widget_font'
/builddir/GIT/tk/lib/tk.rb:3316:in 'TkTreatFont#font_configinfo'
/builddir/GIT/tk/lib/tk.rb:3814:in 'TkConfigMethod#__cget_core'
/builddir/GIT/tk/lib/tk.rb:3835:in 'TkConfigMethod#cget'
/builddir/GIT/tk/lib/tk.rb:3736:in 'TkConfigMethod#[]'
(eval:goldberg.rb):220:in 'TkGoldberg_Demo#do_ctrl_frame'
(eval:goldberg.rb):178:in 'TkGoldberg_Demo#do_display'
(eval:goldberg.rb):156:in 'TkGoldberg_Demo#initialize'
(eval:goldberg.rb):2007:in 'block (2 levels) in Object#eval_samplecode'
./widget:673:in 'Kernel#eval'
./widget:673:in 'block (2 levels) in Object#eval_samplecode'
./widget:646:in 'Proc#call'
./widget:588:in 'PseudoToplevel_Evaluable#pseudo_toplevel_eval'
./widget:670:in 'block in Object#eval_samplecode'
---< backtrace of Tk side >-------
unknown option "-to_ary"
    while executing
```

### PR DESCRIPTION
**Pull request by jeremyevans**
Remove code for Tk 4.*. Tk 8.0 was released in 1997.

Fixes #81

### CODE REVIEW

**Comment by mtasaka** [comment]
Looks good for me, thank you.
