### ISSUE TITLE
Goldberg widget demo does not work with Ruby/Tk 0.6.0 and tk 9.0.2

### ISSUE THREAD

**Issue by mtasaka** [ruby/tk#81]
Trying with Ruby/Tk 0.6.0 with tk 9.0.2, trying

* chdir: `$ cd sample/demos-en`
* execute: `$ ruby ./widget`
* On gui, click `4. A celebration of Rube Goldberg (if supported)`

Then the following error happens:

```
NoMethodError: undefined method 'index' for nil

---< backtrace of Ruby side >-----
./widget:623:in 'method_missing'
/builddir/GIT/tk/lib/tk/font.rb:203:in 'TkFont.is_system_font?'
/builddir/GIT/tk/lib/tk/font.rb:508:in 'TkFont.init_widget_font'
/builddir/GIT/tk/lib/tk.rb:3316:in 'TkTreatFont#font_configinfo'
/builddir/GIT/tk/lib/tk.rb:3814:in 'TkConfigMethod#__cget_core'
/builddir/GIT/tk/lib/tk.rb:3835:in 'TkConfigMethod#cget'
/builddir/GIT/tk/lib/tk.rb:3736:in 'TkConfigMethod#[]'
(eval:goldberg.rb):220:in 'TkGoldberg_Demo#do_ctrl_frame'
(eval:goldberg.rb):178:in 'TkGoldberg_Demo#do_display'
(eval:goldberg.rb):156:in 'TkGoldberg_Demo#initialize'
(eval:goldberg.rb):2007:in 'block (2 levels) in Object#eval_samplecode'
./widget:673:in 'Kernel#eval'
./widget:673:in 'block (2 levels) in Object#eval_samplecode'
./widget:646:in 'Proc#call'
./widget:588:in 'PseudoToplevel_Evaluable#pseudo_toplevel_eval'
./widget:670:in 'block in Object#eval_samplecode'
---< backtrace of Tk side >-------
unknown option "-to_ary"
    while executing
```

**Comment by mtasaka** [comment]
For Goldberg demo, the following patch works:

```
diff --git a/lib/tk/font.rb b/lib/tk/font.rb
index c76481c..a69c728 100644
--- a/lib/tk/font.rb
+++ b/lib/tk/font.rb
@@ -370,7 +370,7 @@ class TkFont
       #r | []
       r.uniq
 
-    when /^8\..*/
+    when /^8\..*/, /^9\..*/
       tk_split_simplelist(tk_call('font', 'names'))
 
     end
```

Looks like some other files / lines have `/^8\..*/` regex, maybe they also need fixing.

```
$ grep -rnI '\^8' .
./lib/tk.rb:2399:      if /^8\.*/ === TK_VERSION  && JAPANIZED_TK
./lib/tk.rb:2407:      if /^8\.*/ === TK_VERSION  && JAPANIZED_TK
./lib/tk.rb:2419:      if /^8\.*/ === TK_VERSION  && JAPANIZED_TK
./lib/tk/xim.rb:51:      if /^8\.*/ === Tk::TK_VERSION  && JAPANIZED_TK
./lib/tk/xim.rb:65:        if /^8\.*/ === Tk::TK_VERSION  && JAPANIZED_TK
./lib/tk/xim.rb:89:      if /^8\.*/ === Tk::TK_VERSION  && JAPANIZED_TK
./lib/tk/font.rb:59:  when /^8\.[0-4]/
./lib/tk/font.rb:125:  when /^8\.[5-9]/, /^9\..*/
./lib/tk/font.rb:353:    when /^8\..*/
./lib/tk/font.rb:373:    when /^8\..*/
./lib/tk/font.rb:435:    when /^8\.[0-4]/
./lib/tk/font.rb:482:    when /^8\.[5-9]/, /^9\..*/
./lib/tk/font.rb:530:      if /^8\..*/ === Tk::TK_VERSION  && JAPANIZED_TK
./lib/tk/font.rb:1589:      if /^8\..*/ === Tk::TK_VERSION  && JAPANIZED_TK
./lib/tk/font.rb:1607:  when /^8\.[0-5]/
./lib/tk/font.rb:2203:  when /^8\.[0-9]/
./sample/demos-jp/style.rb:77:#  when /^8.*/
./sample/demos-jp/widget:51:when /^8.*/
./sample/demos-en/hello:4:#unless /^8\.[1-9]/ =~ Tk::TCL_VERSION && !Tk::JAPANIZED_TK
./sample/demos-en/style.rb:77:#  when /^8.*/
```

**Comment by jeremyevans** [comment]
Thank you for the report. I think we only support Tk 8.4, 8.5, 8.6, and 9.0 (per `ext/tk/extconf.rb`). Checks for other versions should probably be removed. I can work on this tonight.

**Comment by jeremyevans** [comment]
@mtasaka I have submitted #82, which I think should fix this. Can you please review and test it?
